"""Add GameDistribution fields to games table

Revision ID: aaf62441f2ba
Revises: 639659d6cd5d
Create Date: 2026-01-18 13:01:51.611129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf62441f2ba'
down_revision: Union[str, Sequence[str], None] = '639659d6cd5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('gd_game_id', sa.String(length=255), nullable=True))
    op.add_column('games', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('games', sa.Column('embed_url', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('instructions', sa.Text(), nullable=True))
    op.create_index(op.f('ix_games_gd_game_id'), 'games', ['gd_game_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_gd_game_id'), table_name='games')
    op.drop_column('games', 'instructions')
    op.drop_column('games', 'embed_url')
    op.drop_column('games', 'source')
    op.drop_column('games', 'gd_game_id')
    # ### end Alembic commands ###
